### ISSUE TITLE
question: is there a way for the game to end?

### ISSUE THREAD

**Issue by iop3** [RayhanADev/tether#10]
What level (or how many points you scored) will end the game?

**Comment by rayhanadev** [comment]
Well you could crash the game at the [maximum integer limit](https://stackoverflow.com/questions/307179/what-is-javascripts-highest-integer-value-that-a-number-can-go-to-without-losin). Until then it'll "procedurally" generate harder and harder waves!

**Comment by iop3** [comment]
whoa! lol ok xD!
