### ISSUE TITLE
Game not working on Mac (Darwin) with Safari

### ISSUE THREAD

**Issue by darkdarcool** [RayhanADev/tether#11]
**Describe the bug**
When I try to click to start the game, it doesn't start!
**To Reproduce**
Open the link
Try to click to start
**Expected behavior**
I wanted it to start!

**Desktop (please complete the following information):**
 - OS: MAC(darwin)
 - Browser Safari

**Comment by rayhanadev** [comment]
@darkdarcool hmm, it seems to run fine on my computer. I cleared my cache, cookies, storage, etc. just to make sure and it seems fine. I tried it on Windows so maybe it might be a Mac specific issue.

Tried it on Browserstack on Mac running Safari 14. Seems to be a valid issue I'll look into it :)

**Comment by rayhanadev** [comment]
@darkdarcool follow-up is this recent for your Mac or has it always been a thing. If it is recent do you know any specific time that it stopped working (I've been doing a few different things lately).

Also if possible could you please try running it on Chrome or Edge (just to test if it's Safari on Mac specific).

**Comment by darkdarcool** [comment]
![Screen Shot 2021-06-15 at 5 34 08 PM](https://user-images.githubusercontent.com/66882633/122126532-e5c24200-cdff-11eb-9700-1da870d9cc74.png)

There's some info about my computer os

**Comment by darkdarcool** [comment]
It also does work on Google Chrome

**Comment by darkdarcool** [comment]
I do not know when it stopped working, this is my first time playing it in a while. But it worked when you released it on the repl talk

**Comment by darkdarcool** [comment]
And since it’s 2012, you might think it sucks, but it can do everything a newer computer can, at around the same speed

**Comment by 000044Deakin** [comment]
safari is kinda odd though, lots of websites  hate safari

**Comment by darkdarcool** [comment]
Yea, I like safari because of faster loading speed, but I use chrome for websites that don’t support it

**Comment by darkdarcool** [comment]
This issue hasn't had much activity in a while, so lemme close
