### ISSUE TITLE
Add this to Github pages

### ISSUE THREAD

**Issue by BD103** [RayhanADev/tether#2]
Enable Github pages in case Replit dies or for another way to play.

**Comment by rayhanadev** [comment]
I was literally on the Repl with this same thought, comes to Github, and see this issue XD. I set it up, so it should be up in a few :).

**Comment by rayhanadev** [comment]
@BD103 seems to be working with most things except fontawesome which is being super weird. However since most of it is up check it out at https://rayhanadev.github.io/tether.
