### ISSUE TITLE
make the game harder

### ISSUE THREAD

**Issue by iop3** [RayhanADev/tether#9]
you could literally spin your mouse around and around and hit everything. probably should make the ai a bit smarter. ;)

**Comment by rayhanadev** [comment]
The highest scores don't just spin their mouses around :). I watched a Twitch stream of someone playing the game and they had some pretty good tactics. There isn't a need to kill the joys of any new plays lol.

New characters are coming, along with a super hard wave ;D.

**Comment by iop3** [comment]
alright got it!
